### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by alonsofalconi** [bimbolabuari/mv-portfolio#9]
You did a great job with your portfolio website but there are a few recommendations that could improve your code. :smiley: 

### Suggested Changes :recycle: 
- Move the black line on "My Recent Works" title to the right to make it look similar to the original template.
- Add space in the about section between the paragraph and the button. 
- Remove unused classes in styles.css
- Try to use variables for colors for better code maintenance.

Happy coding :clap: :technologist:

**Comment by bimbolabuari** [comment]
@alonsofl, Thanks for the suggested changes observed. It has been implemented and has helped improve my code 👍
